function menu_syninv

global mag2data

%%
% menu_syninv asks if the user want to perform an inversion of synthetic
% data.
%
% Written by Stefano Stocco on September, 2007
% Modified by Stefano Stocco on December, 2008

% Copyright (C) 2007 Stefano Stocco
% 
% This file is part of MAG2DATA.
% 
% MAG2DATA is free software; you can redistribute it and/or modify it
% under the terms of the GNU General Public License as published by the
% Free Software Foundation; either version 3 of the License, or (at your
% option) any later version.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License along
% with this program; if not, see <http://www.gnu.org/licenses>.


%% Inversion-of-synthetic-data figures
figure(...
    'Tag','syn_invmenu',...
    'Menubar','none',...
    'Numbertitle','off',...
    'Units','normalized',...
    'Color',[0.5235    0.5785    0.7471],...
    'Name','  ??',...
    'Position',[0.35 0.4 0.3 0.2],...
    'RendererMode','manual');
syn_invmenu=findobj('Tag','syn_invmenu');

%% Buttons
uicontrol(...
   'Parent',syn_invmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.05 .75 .9 .1],...
   'Enable','on',...
   'String','Do you want to compute 2D inversion?',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',syn_invmenu,...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.2 .35 .2 .2],...
   'Enable','On',...
   'String','Yes',...
   'callback','close(findobj(''Tag'',''syn_invmenu'')); close(findobj(''Tag'',''plot_synfig'')); menu_syninv2');
uicontrol(...
   'Parent',syn_invmenu,...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.6 .35 .2 .2],...
   'Enable','On',...
   'String','No',...
   'Callback','close(findobj(''Tag'',''syn_invmenu''))');

