function menu_syninv2

global mag2data

%%
% menu_syninv2 creates the inversion-of-synthetic-data figure menu, in order
% to  perform an inversion procedure starting from the evaluated synthetic
% data.
%
% Written by Stefano Stocco on December, 2008

% Copyright (C) 2007 Stefano Stocco
% 
% This file is part of MAG2DATA.
% 
% MAG2DATA is free software; you can redistribute it and/or modify it
% under the terms of the GNU General Public License as published by the
% Free Software Foundation; either version 3 of the License, or (at your
% option) any later version.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License along
% with this program; if not, see <http://www.gnu.org/licenses>.


figure(...
    'Tag','invofsynmenu',...
    'Visible','on',...
    'Menubar','none',...
    'Numbertitle','off',...
    'Units','normalized',...
    'Color',[0.5235    0.5785    0.7471],...
    'Name','INVERSION OF SYNTHETIC DATA',...
    'Position',[0.3 0.35 0.4 0.3],...
    'RendererMode','manual');
invofsynmenu=findobj('Tag','invofsynmenu');

%% Inversion-of-synthetic-data parameters
% ---------- Frame 1 ---------- %
uicontrol(...
   'Parent',invofsynmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.07 .45 .35 .45],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Radio buttons ---------- %
uicontrol(...
   'Parent',invofsynmenu,...
   'Tag','campo_totinvofsynbutton',...
   'Visible','on',...
   'Style','radiobutton',...
   'Units','normalized',...
   'Position',[.11 .77 .27 .09],...
   'Enable','on',...
   'String','     Total Field',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Value',0,...
   'Callback','set(findobj(''Tag'',''gradinvofsynbutton''),''Value'',0), set(findobj(''Tag'',''bothFGinvofsynbutton''),''Value'',0); mag2data.controls.conjugatekernels=0;');
uicontrol(...
   'Parent',invofsynmenu,...
   'Tag','gradinvofsynbutton',...
   'Visible','on',...
   'Style','radiobutton',...
   'Units','normalized',...
   'Position',[.11 .63 .27 .09],...
   'Enable','on',...
   'String',' Vertical Gradient',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Value',1,...
   'Callback','set(findobj(''Tag'',''campo_totinvofsynbutton''),''Value'',0), set(findobj(''Tag'',''bothFGinvofsynbutton''),''Value'',0); mag2data.controls.conjugatekernels=0;');
uicontrol(...
   'Parent',invofsynmenu,...
   'Tag','bothFGinvofsynbutton',...
   'Visible','on',...
   'Style','radiobutton',...
   'Units','normalized',...
   'Position',[.11 .49 .27 .09],...
   'Enable','on',...
   'String','Both sensors data',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Value',0,...
   'Callback','set(findobj(''Tag'',''campo_totinvofsynbutton''),''Value'',0), set(findobj(''Tag'',''gradinvofsynbutton''),''Value'',0); mag2data.controls.conjugatekernels=1;');

% ---------- Frame 2 ---------- %
uicontrol(...
   'Parent',invofsynmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .28 0.43 .12],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Random noise ---------- %
uicontrol(...
   'Parent',invofsynmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.05 .31 .25 .06],...
   'Enable','on',...
   'String','Random Noise (%)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',invofsynmenu,...
   'Tag','edit_invofsyn_err_perc',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.34 .3 .1 .08],...
   'Enable','on',...
   'String',[5],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 3 ---------- %
uicontrol(...
   'Parent',invofsynmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.52 .37 0.45 .53],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Inversion parameters ---------- %
uicontrol(...
   'Parent',invofsynmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.51 .86 .29 .06],...
   'Enable','on',...
   'String','Inversion parameters',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',invofsynmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.55 .77 .25 .06],...
   'Enable','on',...
   'String','Max iteration',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',invofsynmenu,...
   'Tag','edit_invofsyn_Max_iter',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.85 .76 .1 .08],...
   'Enable','on',...
   'String',[10],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',invofsynmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.55 .64 .25 .06],...
   'Enable','on',...
   'String','Noise / Signal',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',invofsynmenu,...
   'Tag','edit_invofsyn_l_0',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.85 .63 .1 .08],...
   'Enable','on',...
   'String',[0.05],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',invofsynmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.55 .51 .25 .06],...
   'Enable','on',...
   'String','Susceptibility Contrast',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',invofsynmenu,...
   'Tag','edit_invofsyn_target',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.85 .50 .1 .08],...
   'Enable','on',...
   'String',[0.01],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',invofsynmenu,...
   'Tag','kernelequalization',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.58 .4 .32 .06],...
   'Enable','on',...
   'String','    Kernel equalization',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','@depthweightingbutton; clear ans;');

% ---------- Go! Button ---------- %
uicontrol(...
   'Parent',invofsynmenu,...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.45 .1 .1 .1],...
   'Enable','on',...
   'String','OK',...
   'Callback','invofsyn;');

mag2data.controls.conjugatekernels=0;

function depthweightingbutton
val=get(findobj('Tag','kernelequalization'),'Value');
set(findobj('Tag','kernelequalization'),'Value',abs(val-1));