function menu_filtering

global mag2data

%%
% menu_filtering creates the filtering figure menu, a fast and simple tool
% for data filtering. It is possible to: 1) regularise the sampling
% interval if unevenly sampling data; 2) zero-ped profile to avoid border
% effect; 3) windowing the signals; 4) compute the signal spectrum and 
% apply a butterworth filter or a moving avarage filter.
%
% Written by Stefano Stocco on September, 2007
% Modified by Stefano Stocco on December, 2008

% Copyright (C) 2007 Stefano Stocco
% 
% This file is part of MAG2DATA.
% 
% MAG2DATA is free software; you can redistribute it and/or modify it
% under the terms of the GNU General Public License as published by the
% Free Software Foundation; either version 3 of the License, or (at your
% option) any later version.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License along
% with this program; if not, see <http://www.gnu.org/licenses>.


%% Filtering figure
figure(...
    'Tag','filteringmenu',...
    'Menubar','none',...
    'Visible','on',...
    'Numbertitle','off',...
    'Units','normalized',...
    'Color',[0.5235    0.5785    0.7471],...
    'Name','DATA POST-PROCESSING',...
    'Position',[0.25 0.3 0.5 0.45],...
    'RendererMode','manual');
filteringmenu=findobj('Tag','filteringmenu');

%% Filtering menu
% ---------- Frame 1 ---------- %
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .77 .36 .18],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- File ---------- % 
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.021 .92 .08 .05],...
   'Enable','on',...
   'String','File',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.095 .82 .22 .075],...
   'Enable','on',...
   'String','Load *.txt File',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','showprofile2');

% ---------- Frame 2 ---------- %
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .56 .36 .15],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Resampling ---------- % 
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.021 .68 .2 .05],...
   'Enable','on',...
   'String','Resampling Data',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .6 .22 .06],...
   'Enable','on',...
   'String','Sampling Interval (m)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','edit_fil_dx',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .6 .1 .058],...
   'Enable','on',...
   'String',[1],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 3 ---------- %
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .26 .36 .23],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ------------ Zero padding profile ------------------------    
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.021 .46 .23 .05],...
   'Enable','on',...
   'String','Zero Padding Profile',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .39 .22 .05],...
   'Enable','on',...
   'String','Beginning of Profile',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','edit_fil_zeropadinprof',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .385 .1 .058],...
   'Enable','on',...
   'String',[2],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .3 .22 .05],...
   'Enable','on',...
   'String','End of Profile',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','edit_fil_zeropadfineprof',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .295 .1 .058],...
   'Enable','on',...
   'String',[2],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 4 ---------- %
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .01 .36 .18],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ------------ Spectrum ------------------------    
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.021 .16 .13 .05],...
   'Enable','on',...
   'String','Spectrum',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','computespectrumbutton',...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.095 .06 .22 .075],...
   'Enable','off',...
   'String','Compute spectrum',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','menu_spectrum; spectra; plot_spectra;');

% ---------- Go! Button ---------- %
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','regularsamplingbutton',...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.4 .6 .07 .07],...
   'Enable','off',...
   'String','OK',...
   'Callback','regularsampling;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','zeropadprofilebutton',...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.4 .34 .07 .07],...
   'Enable','off',...
   'String','OK',...
   'Callback','zeropadprofile;');

%% Windows' Type
% ---------- Frame 5 ---------- %
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.61 .01 .36 .94],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ------------ Windows ------------------------    
uicontrol(...
   'Parent',filteringmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 .92 .15 .05],...
   'Enable','off',...
   'String','Windows',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','barthannwin',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .87 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       barthannwin',...
   'Callback','mag2data.controls.finestra=''barthannwin''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','bartlett',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .81 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       bartlett',...
   'Callback','mag2data.controls.finestra=''bartlett''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','blackman',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .75 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       blackman',...
   'Callback','mag2data.controls.finestra=''blackman''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','blackmanharris',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .69 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       blackmanharris',...
   'Callback','mag2data.controls.finestra=''blackmanharris''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','bohmanwin',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .63 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       bohmanwin',...
   'Callback','mag2data.controls.finestra=''bohmanwin''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','chebwin',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .57 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       chebwin',...
   'Callback','mag2data.controls.finestra=''chebwin''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','rchebwin',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.89 .57 .07 .05],...
   'Enable','off',...
   'String',[100],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','flattopwin',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .51 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       flattopwin',...
   'Callback','mag2data.controls.finestra=''flattopwin''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','gausswin',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .45 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       gausswin',...
   'Callback','mag2data.controls.finestra=''gausswin''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','hamming',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .39 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       hamming',...
   'Callback','mag2data.controls.finestra=''hamming''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','hann',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .33 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       hann',...
   'Callback','mag2data.controls.finestra=''hann''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','kaiser',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .27 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       kaiser',...
   'Callback','mag2data.controls.finestra=''kaiser''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','betakaiser',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.89 .27 .07 .05],...
   'Enable','off',...
   'String',[0.5],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','nuttallwin',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .21 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       nuttallwin',...
   'Callback','mag2data.controls.finestra=''nuttallwin''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','parzenwin',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .15 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       parzenwin',...
   'Callback','mag2data.controls.finestra=''parzenwin''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','tukeywin',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .09 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       tukeywin',...
   'Callback','mag2data.controls.finestra=''tukeywin''; finestra;');
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','rtukeywin',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.89 .09 .07 .05],...
   'Enable','off',...
   'String',[0.5],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','triang',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.63 .03 .25 .05],...
   'Enable','off',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'String','       triang',...
   'Callback','mag2data.controls.finestra=''triang''; finestra;');

% ---------- Go! Button ---------- %
uicontrol(...
   'Parent',filteringmenu,...
   'Tag','finestrabutton',...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.53 .03 .07 .07],...
   'Enable','off',...
   'String','OK',...
   'Callback','mag2data.fileout=[mag2data.x mag2data.Fout]; saveXF;');