function menu_spectrum

global mag2data

%%
% menu_spectrum creates the spectrum figure menu, in order to compute the
% signal spectrum and filter the data. It is possible to choose between two
% types of filter: 1) moving avarage filter; 2) Butterworth filter.
%
% Written by Stefano Stocco on September, 2007
% Modified by Stefano Stocco on December, 2008

% Copyright (C) 2007 Stefano Stocco
% 
% This file is part of MAG2DATA.
% 
% MAG2DATA is free software; you can redistribute it and/or modify it
% under the terms of the GNU General Public License as published by the
% Free Software Foundation; either version 3 of the License, or (at your
% option) any later version.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License along
% with this program; if not, see <http://www.gnu.org/licenses>.


%% Spectrum figure
figure(...
    'Tag','spectrummenu',...
    'Menubar','none',...
    'Visible','on',...
    'Numbertitle','off',...
    'Units','normalized',...
    'Color',[0.5235    0.5785    0.7471],...
    'Name','FILTERING DATA',...
    'Position',[0.01 0.05 0.98 0.9],...
    'RendererMode','manual');
spectrummenu=findobj('Tag','spectrummenu');

%% Axis
axes(...
   'Parent',spectrummenu,...
   'Tag','assi_amp',...
   'Position',[0.05  0.59  0.42  0.4],...
   'XGrid','On',...
   'YGrid','On',...
   'Visible','On');
axes(...
   'Parent',spectrummenu,...
   'Tag','assi_dB',...
   'Position',[0.05  0.1  0.42  0.4],...
   'XGrid','On',...
   'YGrid','On',...
   'Visible','On');
axes(...
   'Parent',spectrummenu,...
   'Tag','assi_lam',...
   'Position',[0.05  0.06  0.42  0.0001],...
   'Color',[0.5235    0.5785    0.7471],...
   'XGrid','Off',...
   'YGrid','Off',...
   'Visible','On');
axes(...
   'Parent',spectrummenu,...
   'Tag','assi_profilo',...
   'Position',[0.55  0.59  0.42  0.4],...
   'XGrid','On',...
   'YGrid','On',...
   'Visible','On');

% ---------- Frame 1 ---------- %
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.55 .43 .41 .07],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Moving Avarage Filter Parameters ---------- %
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'FontSize',9,...
   'Units','normalized',...
   'Position',[.55 .48 .13 .03],...
   'Enable','on',...
   'String','Moving Average Filter',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 .45 .05 .025],...
   'Enable','on',...
   'String','Points',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',spectrummenu,...
   'Tag','movingavaragepoints',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.67 .448 .06 .029],...
   'Enable','on',...
   'String',[5],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 2 ---------- %
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.55 .09 .41 .31],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Butterworth Filter Parameters ---------- %
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'FontSize',9,...
   'Units','normalized',...
   'Position',[.55 .38 .11 .03],...
   'Enable','on',...
   'String','Butterworth Filter',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 .34 .05 .025],...
   'Enable','on',...
   'String','Wp',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',spectrummenu,...
   'Tag','edit_fil_Wp',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.67 .338 .06 .029],...
   'Enable','on',...
   'String',[1],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.8 .34 .05 .025],...
   'Enable','on',...
   'String','Rp',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',spectrummenu,...
   'Tag','edit_fil_Rp',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.87 .338 .04 .029],...
   'Enable','on',...
   'String',[1],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 .29 .05 .025],...
   'Enable','on',...
   'String','Ws',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',spectrummenu,...
   'Tag','edit_fil_Ws',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.67 .288 .06 .029],...
   'Enable','on',...
   'String',[2],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.8 .29 .05 .025],...
   'Enable','on',...
   'String','Rs',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',spectrummenu,...
   'Tag','edit_fil_Rs',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.87 .288 .04 .029],...
   'Enable','on',...
   'String',[30],...
   'Backgroundcolor',[1 1 1]);

%% Help
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'FontSize',9,...
   'Units','normalized',...
   'Position',[.58 .22 .18 .03],...
   'Enable','on',...
   'String','Low-pass filter:       Wp < Ws',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'FontSize',9,...
   'Units','normalized',...
   'Position',[.58 .18 .18 .03],...
   'Enable','on',...
   'String','High-pass filter:      Wp > Ws',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'FontSize',9,...
   'Units','normalized',...
   'Position',[.58 .14 .3 .03],...
   'Enable','on',...
   'String','Band-pass filter:      Ws(1) < Wp(1) < Wp(2) < Ws(2)',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','text',...
   'FontSize',9,...
   'Units','normalized',...
   'Position',[.58 .1 .3 .03],...
   'Enable','on',...
   'String','Band-stop filter:      Wp(1) < Ws(1) < Ws(2) < Wp(2)',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);

% ---------- Go Button! ---------- %
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.813 .442 .09 .045],...
   'Enable','on',...
   'String','Filtering',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','mag2data.controls.filtertype=''movingavarage''; filtering; set(findobj(''Tag'',''savefiltbutton''),''Enable'',''on'')');
uicontrol(...
   'Parent',spectrummenu,...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.813 .21 .09 .045],...
   'Enable','on',...
   'String','Filtering',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','mag2data.controls.filtertype=''butterworth''; filtering; set(findobj(''Tag'',''savefiltbutton''),''Enable'',''on'')');
uicontrol(...
   'Parent',spectrummenu,...
   'Tag','savefiltbutton',...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.7 .02 .1 .05],...
   'Enable','off',...
   'String','Save',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','mag2data.fileout=[mag2data.x mag2data.Fout]; saveXF; close(findobj(''Tag'',''spectrummenu''))');