function menu_inv2d

global mag2data

%%
% menu_inv2d creates the inversion figure menu, in order to perform an
% inversion procedure of a magnetic data set.
%
% Written by Stefano Stocco on September, 2007
% Modified by Stefano Stocco on December, 2008

% Copyright (C) 2007 Stefano Stocco
% 
% This file is part of MAG2DATA.
% 
% MAG2DATA is free software; you can redistribute it and/or modify it
% under the terms of the GNU General Public License as published by the
% Free Software Foundation; either version 3 of the License, or (at your
% option) any later version.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License along
% with this program; if not, see <http://www.gnu.org/licenses>.


%% Inversion figure
figure(...
    'Tag','inversionmenu',...
    'Menubar','none',...
    'Visible','on',...
    'Numbertitle','off',...
    'Units','normalized',...
    'Color',[0.5235    0.5785    0.7471],...
    'Name','2D INVERSION',...
    'Position',[0.25 0.3 0.5 0.45],...
    'RendererMode','manual');
inversionmenu=findobj('Tag','inversionmenu');

%% Inversion menu

% ---------- Frame 1 ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .6 .36 .35],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- File ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.021 .92 .08 .05],...
   'Enable','on',...
   'String','File',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.08 .84 .22 .075],...
   'Enable','on',...
   'String','Load *.txt File',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','loadfile; lunghezza_profilo;');
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','campo_totinvbutton',...
   'Visible','on',...
   'Style','radiobutton',...
   'Units','normalized',...
   'Position',[.04 .73 .16 .075],...
   'Enable','on',...
   'String','    Total Field',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Value',0,...
   'Callback','set(findobj(''Tag'',''gradinvbutton''),''Value'',0)');
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','gradinvbutton',...
   'Visible','on',...
   'Style','radiobutton',...
   'Units','normalized',...
   'Position',[.22 .73 .16 .075],...
   'Enable','on',...
   'String','Vertical Gradient',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Value',1,...
   'Callback','set(findobj(''Tag'',''campo_totinvbutton''),''Value'',0)');
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .64 .22 .05],...
   'Enable','on',...
   'String','Profile length  (m)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .64 .1 .055],...
   'Enable','off',...
   'String',[],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 2 ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .43 .36 .12],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Data interpolation ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.021 .52 .2 .05],...
   'Enable','on',...
   'String','Data Interpolation',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .46 .22 .05],...
   'Enable','on',...
   'String','Order of interpolation',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_order',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .46 .1 .055],...
   'Enable','on',...
   'String',[1],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 3 ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .01 .36 .37],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Prisms ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.021 .35 .1 .05],...
   'Enable','on',...
   'String','Prisms',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .29 .22 .05],...
   'Enable','on',...
   'String','Prisms along x',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_CX',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .29 .1 .055],...
   'Enable','on',...
   'String',[25],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .20 .22 .05],...
   'Enable','on',...
   'String','Prisms along z',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_CZ',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .20 .1 .055],...
   'Enable','on',...
   'String',[5],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .11 .22 .05],...
   'Enable','on',...
   'String','Thickness (m)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_dz',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .11 .1 .055],...
   'Enable','on',...
   'String',[2],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','inv2dresbutton',...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.04 .02 .14 .07],...
   'Enable','off',...
   'String','Resolution',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','resmodinv;');
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.2 .02 .18 .07],...
   'Enable','on',...
   'String','Load Initial Model',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','loadpam;');

% ---------- Frame 4 ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.61 .64 .36 .31],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Magnetic field parameters ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.601 .92 .1 .05],...
   'Enable','on',...
   'String','Field',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .845 .22 .08],...
   'Enable','on',...
   'String','Total Field Intensity (nT)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_F',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .86 .1 .055],...
   'Enable','on',...
   'String',[46000],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .77 .22 .05],...
   'Enable','on',...
   'String','Inclination I (°)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_I',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .77 .1 .055],...
   'Enable','on',...
   'String',[60],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .66 .22 .09],...
   'Enable','on',...
   'String','Angle Profile Direction / Magnetic North (°)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_Beta',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .68 .1 .055],...
   'Enable','on',...
   'String',[0],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 5 ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.61 .39 .36 .2],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Height of Sensors ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.601 .56 .22 .05],...
   'Enable','on',...
   'String','Height of Sensors',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .50 .22 .05],...
   'Enable','on',...
   'String','Bottom sensor (m)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_hsi',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .50 .1 .055],...
   'Enable','on',...
   'String',[0.3],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .42 .22 .05],...
   'Enable','on',...
   'String','Top Sensor (m)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_hss',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .42 .1 .055],...
   'Enable','on',...
   'String',[1.3],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 6 ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.61 .01 .36 .33],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Inversion parameters ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.602 .31 .25 .05],...
   'Enable','on',...
   'String','Inversion Parameters',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .25 .22 .05],...
   'Enable','on',...
   'String','Max interation',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_Max_iter',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .25 .1 .055],...
   'Enable','on',...
   'String',[10],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .17 .22 .05],...
   'Enable','on',...
   'String','Noise / signal',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_l_0',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .17 .1 .055],...
   'Enable','on',...
   'String',[0.125],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .09 .22 .05],...
   'Enable','on',...
   'String','Susceptibility Contrast',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','edit_inv_target',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .09 .1 .055],...
   'Enable','on',...
   'String',[0.01],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','kernelequalization',...
   'Visible','on',...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.66 .02 .25 .05],...
   'Enable','on',...
   'String','    Kernel equalization',...
   'Value',0,...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','@depthweightingbutton; clear ans;');

% ---------- Go! Button ---------- %
uicontrol(...
   'Parent',inversionmenu,...
   'Tag','inv2dokbutton',...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.40 .05 .09 .08],...
   'Enable','off',...
   'String','OK',...
   'Callback','inv2d;');
uicontrol(...
   'Parent',inversionmenu,...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.42 .85 .16 .1],...
   'Enable','on',...
   'String','Main Window',...
   'BackgroundColor',[1 0 0],...
   'Callback','close(findobj(''Tag'',''inversionmenu'')); close(findobj(''Tag'',''modelmenu'')); set(findobj(''Tag'',''mainmenu''),''Visible'',''on'')');

% uicontrol(...
%    'Parent',inversionmenu,...
%    'Visible','on',...
%    'Style','pushbutton',...
%    'Units','normalized',...
%    'Position',[.51 .05 .09 .08],...
%    'Enable','on',...
%    'String','Help',...
%    'Callback','set(findobj(''Tag'',''help_invfig''),''visible'',''on'')');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function depthweightingbutton
val=get(findobj('Tag','kernelequalization'),'Value');
set(findobj('Tag','kernelequalization'),'Value',abs(val-1));