function menu_forward

global mag2data

%%
% menu_forward creates the forward figure menu, in order to compute the
% forward modelling of a magnetic body (trial-and-error method).
%
% Written by Stefano Stocco on September, 2007
% Modified by Stefano Stocco on December, 2008

% Copyright (C) 2007 Stefano Stocco
% 
% This file is part of MAG2DATA.
% 
% MAG2DATA is free software; you can redistribute it and/or modify it
% under the terms of the GNU General Public License as published by the
% Free Software Foundation; either version 3 of the License, or (at your
% option) any later version.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License along
% with this program; if not, see <http://www.gnu.org/licenses>.


%% Forward figure
figure(...
    'Tag','forwardmenu',...
    'Menubar','none',...
    'Visible','on',...
    'Numbertitle','off',...
    'Units','normalized',...
    'Color',[0.5235    0.5785    0.7471],...
    'Name','FORWARD MODELING',...
    'Position',[0.25 0.35 0.5 0.4],...
    'RendererMode','manual');
forwardmenu=findobj('Tag','forwardmenu');

%% Forward menu
% ---------- Frame 1 ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .7 .36 .25],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- File ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.022 .92 .07 .05],...
   'Enable','on',...
   'String','File',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.095 .84 .22 .07],...
   'Enable','on',...
   'String','Load *.txt File',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Callback','loadfile; punti_sperimentali;');
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','campo_totforbutton',...
   'Visible','on',...
   'Style','radiobutton',...
   'Units','normalized',...
   'Position',[.045 .74 .16 .06],...
   'Enable','on',...
   'String','Total Field',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Value',0,...
   'Callback','set(findobj(''Tag'',''gradforbutton''),''Value'',0)');
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','gradforbutton',...
   'Visible','on',...
   'Style','radiobutton',...
   'Units','normalized',...
   'Position',[.221 .74 .16 .06],...
   'Enable','on',...
   'String','  Gradient',...
   'Backgroundcolor',[0.7    0.75    0.85],...
   'Value',1,...
   'Callback','set(findobj(''Tag'',''campo_totforbutton''),''Value'',0)');

% ---------- Frame 2 ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .5 .36 .15],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Data interpolation ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.021 .62 .2 .05],...
   'Enable','on',...
   'String','Data Interpolation',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .55 .22 .05],...
   'Enable','on',...
   'String','Order of Interpolation',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','edit_for_order',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .55 .1 .058],...
   'Enable','on',...
   'String',[1],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 3 ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.03 .02 .36 .43],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Prisms ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.021 .42 .1 .05],...
   'Enable','on',...
   'String','Prisms',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .35 .22 .05],...
   'Enable','on',...
   'String','Prisms along x',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','edit_for_CX',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .35 .1 .058],...
   'Enable','on',...
   'String',[25],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .25 .22 .05],...
   'Enable','on',...
   'String','Prisms along z',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','edit_for_CZ',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .25 .1 .058],...
   'Enable','on',...
   'String',[5],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.04 .15 .22 .05],...
   'Enable','on',...
   'String','Thickness (m)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','edit_for_dz',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.275 .15 .1 .058],...
   'Enable','on',...
   'String',[2],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
    'Parent',forwardmenu,...
    'Tag','modelbutton',...
    'Visible','on',...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',[.08 .05 .25 .065],...
    'Enable','off',...
    'String','Model',...
    'Callback','mag2data.model.lp=str2num(get(findobj(''Tag'',''edit_for_lp''),''string'')); mag2data.model.CX=str2num(get(findobj(''Tag'',''edit_for_CX''),''string'')); mag2data.model.CZ=str2num(get(findobj(''Tag'',''edit_for_CZ''),''string'')); mag2data.model.dz=str2num(get(findobj(''Tag'',''edit_for_dz''),''string'')); set(findobj(''Tag'',''forwardmenu''),''visible'',''off''); model_for;');

% ---------- Frame 4 ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.61 .61 .36 .34],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Magnetic field parameters ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.601 .92 .09 .05],...
   'Enable','on',...
   'String','Field Data',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .83 .22 .085],...
   'Enable','on',...
   'String','Total Field Intensity F (nT)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','edit_for_F',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .85 .1 .058],...
   'Enable','on',...
   'String',[46000],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .75 .22 .05],...
   'Enable','on',...
   'String','Inclination I (°)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','edit_for_I',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .75 .1 .058],...
   'Enable','on',...
   'String',[60],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .63 .22 .09],...
   'Enable','on',...
   'String','Angle Profile Direction / Magnetic North (°)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','edit_for_Beta',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .65 .1 .058],...
   'Enable','on',...
   'String',[0],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 5 ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.61 .32 .36 .24],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Height of Sensors ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.601 .53 .2 .05],...
   'Enable','on',...
   'String','Height of Sensors',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .45 .22 .05],...
   'Enable','on',...
   'String','Bottom Sensor (m)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','edit_for_hsi',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .45 .1 .058],...
   'Enable','on',...
   'String',[0.3],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .36 .22 .05],...
   'Enable','on',...
   'String','Top Sensor (m)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','edit_for_hss',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .36 .1 .058],...
   'Enable','on',...
   'String',[1.3],...
   'Backgroundcolor',[1 1 1]);

% ---------- Frame 6 ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.61 .02 .36 .24],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Profile ---------- % 
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 .23 .08 .05],...
   'Enable','on',...
   'String','Profile',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .16 .22 .05],...
   'Enable','on',...
   'String','Number of Data',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .16 .1 .058],...
   'Enable','off',...
   'String',[],...
   'Backgroundcolor',[1 1 1]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.62 .06 .22 .05],...
   'Enable','on',...
   'String','Profile length (m)',...
   'Backgroundcolor',[0.7    0.75    0.85]);
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.855 .06 .1 .058],...
   'Enable','off',...
   'String',[],...
   'Backgroundcolor',[1 1 1]);


% ---------- Go! Button ---------- %
uicontrol(...
   'Parent',forwardmenu,...
   'Tag','forwardokbutton',...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.40 .05 .09 .08],...
   'Enable','off',...
   'String','OK',...
   'Callback','forward;');
uicontrol(...
   'Parent',forwardmenu,...
   'Visible','on',...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.42 .85 .16 .1],...
   'Enable','on',...
   'String','Main Window',...
   'BackgroundColor',[1 0 0],...
   'Callback','close(findobj(''Tag'',''forwardmenu'')); close(findobj(''Tag'',''modelmenu'')); set(findobj(''Tag'',''mainmenu''),''Visible'',''on'')');

% uicontrol(...
%    'Parent',forwardmenu,...
%    'Tag','forwardhelpbutton',...
%    'Visible','on',...
%    'Style','pushbutton',...
%    'Units','normalized',...
%    'Position',[.51 .05 .09 .08],...
%    'Enable','on',...
%    'String','Help',...
%    'Callback','set(findobj(''Tag'',''help_formenu''),''visible'',''on'')');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

mag2data.controls.sequenzaBeta=1;
mag2data.controls.alreadyforward=0;