function model_for

global mag2data

%%
% model_for creates the model figure menu for forward modelling.
%
% Written by Stefano Stocco on September, 2007
% Modified by Stefano Stocco on December, 2008

% Copyright (C) 2007 Stefano Stocco
% 
% This file is part of MAG2DATA.
% 
% MAG2DATA is free software; you can redistribute it and/or modify it
% under the terms of the GNU General Public License as published by the
% Free Software Foundation; either version 3 of the License, or (at your
% option) any later version.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License along
% with this program; if not, see <http://www.gnu.org/licenses>.

% ------------------------ CREATE MODEL FIGURE
% -----------------------------------
%% Model menu
figure(...
    'Tag','modelmenu',...
    'Numbertitle','off',...
    'Units','normalized',...
    'Name','MODEL',...
    'Color',[0.5235    0.5785    0.7471],...
    'Position',[0.01 0.05 0.98 0.88],...
    'RendererMode','manual');
modelmenu=findobj('Tag','modelmenu');
    
% ---------- Frame 1 ---------- %
uicontrol(...
   'Parent',modelmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.05 .005 .27 .08],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Susceptibility ---------- %
uicontrol(...
   'Parent',modelmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.06 .02 .063 .05],...
   'Enable','on',...
   'String','Susceptibility Contrast (SI)',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
uicontrol(...
   'Parent',modelmenu,...
   'Tag','edit_for_model_sus_celle',...
   'Visible','on',...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.13 .025 .06 .04],...
   'Enable','on',...
   'String',[0.01],...
   'Backgroundcolor',[1 1 1]);

%% ------------ Buttons -------------
uicontrol(...
   'Parent',modelmenu,...
   'Tag','applymodelbutton',...
   'style','pushbutton',...
   'units','normalized',...
   'Position',[.23 .02 .07 .05],...
   'Enable','Off',...
   'String','Apply',...
   'Callback','mag2data.model.sus_celle=str2num(get(findobj(''Tag'',''edit_for_model_sus_celle''),''string'')); apply;');
uicontrol(...
   'Parent',modelmenu,...
   'Tag','selectprismsmodelbutton',...
   'style','pushbutton',...
   'units','normalized',...
   'Position',[.4 .02 .08 .05],...
   'Enable','On',...
   'String','Select prisms',...
   'Callback','[mag2data.model.x_click,mag2data.model.z_click]=ginput; dist;');
uicontrol(...
   'Parent',modelmenu,...
   'Tag','selectareamodelbutton',...
   'style','pushbutton',...
   'units','normalized',...
   'Position',[.5 .02 .08 .05],...
   'Enable','On',...
   'String','Select area',...
   'Callback','select_area');
uicontrol(...
   'Parent',modelmenu,...
   'Tag','deselectmodelbutton',...
   'style','pushbutton',...
   'units','normalized',...
   'Position',[.65 .02 .08 .05],...
   'Enable','Off',...
   'String','Deselect',...
   'Callback','[mag2data.model.x_des,mag2data.model.z_des]=ginput; deselect;');
uicontrol(...
   'Parent',modelmenu,...
   'Tag','savemodelbutton',...
   'style','pushbutton',...
   'units','normalized',...
   'Position',[.8 .02 .08 .05],...
   'Enable','Off',...
   'String','Save model',...
   'Callback','savefor;');
uicontrol(...
   'Parent',modelmenu,...
   'Tag','okmodelbutton',...
   'style','pushbutton',...
   'units','normalized',...
   'Position',[.9 .02 .07 .05],...
   'Enable','Off',...
   'String','OK',...
   'Callback','set(findobj(''Tag'',''modelmenu''),''Visible'',''off''), set(findobj(''Tag'',''forwardmenu''),''Visible'',''on'');  close (findobj(''Tag'',''explmenu''))');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Explanation menu
figure(...
    'Tag','explmenu',...
    'Menubar','none',...
    'Numbertitle','off',...
    'Units','normalized',...
    'Name','HELP',...
    'Color',[0.5235    0.5785    0.7471],...
    'Position',[0.35 0.5 0.3 0.2],...
    'RendererMode','manual');
explmenu=findobj('Tag','explmenu');
    
% ---------- Frame ---------- %
uicontrol(...
   'Parent',explmenu,...
   'Visible','on',...
   'Style','frame',...
   'Units','normalized',...
   'Position',[.05 .1 .9 .8],...
   'Enable','on',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);
% ---------- Explanation ---------- %
uicontrol(...
   'Parent',explmenu,...
   'Visible','on',...
   'Style','text',...
   'Units','normalized',...
   'Position',[.1 .2 .8 .6],...
   'Enable','on',...
   'FontSize',10,...
   'String','Creat graphically your subsoil model selecting the prisms and fixing the susceptibility contrast. Read the HELP file (the "Forward modelling" paragraph) for more information.',...
   'Backgroundcolor',[0.5235    0.5785    0.7471]);

grigliassi;

%% Axes for experimental and calculated data
mag2data.hh=axes(...
   'Tag','assi_mod',...
   'Parent',findobj('Tag','modelmenu'),...
   'Position',[0.05 0.6 0.87 0.35],...
   'XGrid','On',...
   'YGrid','On',...
   'Visible','On');

plot(mag2data.xx,mag2data.Fobs,'.', 'MarkerSize',8);
legend('Observed data')
ylabel('Magnetic anomaly (nT or nT/m)')
set(gca,'XLim',[min(mag2data.xx) max(mag2data.xx)], 'XTickLabel',[])


mag2data.model.sus=zeros(mag2data.model.CTOT,1);
mag2data.controls.model.immagine=0;

set(findobj('Tag','modelbutton'),'Enable','off');
set(findobj('Tag','forwardokbutton'),'Enable','on');