function punti_sperimentali

global mag2data

%%
% Punti_sperimentali writes the values of "length of profile" and "number 
% of data" into the forward menu.
%
% Written by Stefano Stocco on September, 2007
% Modified by Stefano Stocco on December, 2008

% Copyright (C) 2007 Stefano Stocco
% 
% This file is part of MAG2DATA.
% 
% MAG2DATA is free software; you can redistribute it and/or modify it
% under the terms of the GNU General Public License as published by the
% Free Software Foundation; either version 3 of the License, or (at your
% option) any later version.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License along
% with this program; if not, see <http://www.gnu.org/licenses>.

if mag2data.controls.annulla==0
    
    forwardmenu=findobj('Tag','forwardmenu');

    uicontrol(...
       'Parent',forwardmenu,...
       'Tag','edit_for_lp',...
       'Visible','on',...
       'Style','edit',...
       'Units','normalized',...
       'Position',[.855 .06 .1 .058],...
       'Enable','off',...
       'String',sprintf('%.0f',mag2data.lp),...
       'Backgroundcolor',[1 1 1]);

    uicontrol(...
       'Parent',forwardmenu,...
       'Tag','edit_for_N_dati',...
       'Visible','on',...
       'Style','edit',...
       'Units','normalized',...
       'Position',[.855 .16 .1 .058],...
       'Enable','off',...
       'String',sprintf('%.0f',mag2data.N_dati_ori),...
       'Backgroundcolor',[1 1 1]);
end